{% set name = "kangas" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/comet-ml/kangas/archive/{{ version }}.tar.gz
  sha256: 0f6d17eae253f6b6735ea89be410da0a064d31bfe8e0c7c4c19a04f33a37b58b

build:
  entry_points:
    - kangas = kangas.cli:main
  noarch: python
  script:
    - cd backend
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - astor
    - numpy
    - tornado
    - matplotlib-base
    - pillow
    - python >=3.7
    - scipy
    - nodejs >=16.15.1a4
    - requests
    - tqdm
    - psutil

test:
  imports:
    - kangas
    - kangas.cli
    - kangas.server
    - kangas.datatypes
  commands:
    - kangas --help

about:
  home: https://github.com/comet-ml/kangas
  doc_url: https://github.com/comet-ml/kangas/wiki
  license: Apache-2.0
  license_file: LICENSE
  summary: Python API for logging large tables of data with visual interface for performing complex queries

extra:
  recipe-maintainers:
    - thewchan
