{% set name = "kangas" %}
{% set version = "2.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/comet-ml/kangas/archive/{{ version }}.tar.gz
  sha256: d8bb66316d7eff1a36483f22d6d071d21779e14259866715c3ff28e91361a1a6

build:
  entry_points:
    - kangas = kangas.cli:main
  noarch: python
  script:
    - cd backend
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - astor
    - click
    - flask >=2.2
    - flask-caching
    - marko
    - matplotlib-base
    - nodejs >=16.15.1a4
    - numpy
    - pillow
    - psutil
    - pyngrok
    - python >=3.7
    - requests
    - scipy
    - scikit-learn
    - waitress


test:
  source_files:
    - backend/tests
  imports:
    - kangas
    - kangas.cli
    - kangas.server
    - kangas.datatypes
  commands:
    - kangas --help

    # Skip pip check because it wants nodejs-bin and we're giving it nodejs
#     - pip check
    - pytest -vvv --capture=tee-sys backend/tests
  requires:
    - pandas <2.1.0  # pandas 2.1+ deprecated _testing.makeMissingDataframe
    - pip
    - pytest

about:
  home: https://github.com/comet-ml/kangas
  doc_url: https://github.com/comet-ml/kangas/wiki
  license: Apache-2.0
  license_file: LICENSE
  summary: Python API for logging large tables of data with visual interface for performing complex queries

extra:
  recipe-maintainers:
    - thewchan
